### PR TITLE
Add Skip List implementation (work in progress)

### PR DESCRIPTION
**Pull request by gmelodie**
1. Add skip list
2. Refactor lists directories
3. Unify lists `README` files

### CODE REVIEW

**Comment by ektagarg** [comment]
Hey! Do not make changes to the existing directory structure. If you want to add skiplist, make another directory or add it to the relevant directory.
Thanks.

**Comment by gmelodie** [comment]
@ektagarg  Does that mean (1) you're not willing to change the directory structure or (2) that the changes I made don't make sense (if so, could you elaborate on that?) or (3) that you are willing to discuss that but in another issue/PR?

**Comment by ektagarg** [comment]
@gmelodie would like to discuss the need to change the directory structure.

**Comment by gmelodie** [comment]
Hey! Sry for the delay. It's been a while but I remember my argument being sth like code reuse so that I could build on top of other data structures. For example, it would be nice to use the linked list implementation to build the skip list.

If I recall correctly the current structure doesn't let me import code from other data structures. I'm far from being a go expert though, so let me know if I'm saying sth stupid :)

**Pull request merged**
